# Generated by Django 3.1.4 on 2021-01-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('application_fee', models.CharField(blank=True, max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('demnd_letter', models.FileField(blank=True, upload_to='jobs/%Y/%m/%d/')),
                ('sample_contract', models.FileField(blank=True, upload_to='jobs/%Y/%m/%d/')),
                ('powers_of_attoney', models.FileField(blank=True, upload_to='jobs/%Y/%m/%d/')),
                ('order_approval', models.FileField(blank=True, upload_to='jobs/%Y/%m/%d/')),
            ],
        ),
    ]
