# Generated by Django 3.1.4 on 2021-01-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('settings', '0002_auto_20210104_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.jobcategory', verbose_name='Job Category'),
        ),
        migrations.AddField(
            model_name='job',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.destination'),
        ),
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.employer'),
        ),
        migrations.AddField(
            model_name='job',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.partner'),
        ),
    ]
