# Generated by Django 3.1.4 on 2021-01-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210104_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cretaed',
            new_name='created',
        ),
    ]
