# Generated by Django 3.1.4 on 2021-01-03 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=100, verbose_name='Email Address')),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
