# Generated by Django 3.1.5 on 2021-02-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_client_trainings'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Training',
        ),
    ]
