# Generated by Django 3.1.4 on 2021-01-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210104_1349'),
        ('settings', '0002_auto_20210104_1349'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.stage')),
            ],
        ),
    ]
