# Generated by Django 3.1.5 on 2021-01-19 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('established', models.DateTimeField(verbose_name='Date of Establishment')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (0, 'Female')])),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email Address')),
                ('reason', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=50)),
                ('registered', models.BooleanField(default=False)),
                ('reg_fee', models.IntegerField(choices=[(1, 'Paid'), (0, 'Not Paid')], default=0, verbose_name='Registration Fee')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('application_fee', models.CharField(blank=True, max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('demnd_letter', models.FileField(blank=True, upload_to='jobs/%Y/%m/%d/')),
                ('sample_contract', models.FileField(blank=True, upload_to='jobs/%Y/%m/%d/')),
                ('powers_of_attoney', models.FileField(blank=True, upload_to='jobs/%Y/%m/%d/')),
                ('order_approval', models.FileField(blank=True, upload_to='jobs/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
