# Generated by Django 3.1.5 on 2021-01-19 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.category', verbose_name='Job Category'),
        ),
        migrations.AddField(
            model_name='job',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.partner'),
        ),
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.branch'),
        ),
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.job'),
        ),
        migrations.AddField(
            model_name='client',
            name='publicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.publicity'),
        ),
        migrations.AddField(
            model_name='client',
            name='stages',
            field=models.ManyToManyField(blank=True, to='settings.Stage'),
        ),
        migrations.AddField(
            model_name='client',
            name='trainings',
            field=models.ManyToManyField(blank=True, to='settings.Training'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
    ]
