# Generated by Django 3.1.5 on 2021-01-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210119_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created']},
        ),
    ]
