# Generated by Django 3.1.5 on 2021-02-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210121_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='trainings',
        ),
    ]
