# Generated by Django 3.1.5 on 2021-01-19 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client'),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client'),
        ),
    ]
