# Generated by Django 3.1.4 on 2021-01-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210104_1349'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(blank=True, upload_to='client/%Y/%m/%d/', verbose_name='Passport Size')),
                ('full', models.ImageField(blank=True, upload_to='client/%Y/%m/%d/', verbose_name='Full Size')),
                ('others', models.ImageField(upload_to='client/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
