# Generated by Django 3.1.4 on 2021-01-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210105_1029'),
        ('files', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
