# Generated by Django 3.1.5 on 2021-01-19 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('files', '0002_auto_20210119_1120'),
        ('home', '0002_auto_20210119_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_no', models.CharField(max_length=100, unique=True, verbose_name='Visa Number')),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('validity', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('document', models.FileField(blank=True, upload_to='clients/%Y/%m/%d/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.agent')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='Vetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('subcounty', models.CharField(blank=True, max_length=100)),
                ('parish', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('date_ob', models.DateField(blank=True, verbose_name='Date Of Birth')),
                ('diso', models.BooleanField(default=False, verbose_name='DISO Approval')),
                ('giso', models.BooleanField(default=False, verbose_name='GISO Approval')),
                ('training', models.BooleanField(default=False, verbose_name='Training Approval')),
                ('ministry', models.BooleanField(default=False, verbose_name='Ministry Approval')),
                ('musaned', models.BooleanField(default=False, verbose_name='Musaned Approval')),
                ('waqala', models.BooleanField(default=False, verbose_name='Waqala Approval')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('document', models.FileField(blank=True, upload_to='clients/%Y/%m/%d/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.destination')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.employer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.job')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('document', models.FileField(blank=True, upload_to='clients/%Y/%m/%d/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=100, unique=True, verbose_name='Ticket Number')),
                ('airline', models.CharField(blank=True, max_length=100)),
                ('checkin', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('document', models.FileField(blank=True, upload_to='clients/%Y/%m/%d/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.agent')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_no', models.CharField(max_length=100, unique=True, verbose_name='Passport Number')),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('place_ob', models.CharField(blank=True, max_length=100, verbose_name='Place Of Birth')),
                ('date_ob', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('document', models.FileField(blank=True, upload_to='clients/%Y/%m/%d/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.agent')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='OtherOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('document', models.FileField(blank=True, upload_to='clients/%Y/%m/%d/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_type', models.IntegerField(choices=[(0, 'Pre-Medical'), (1, 'Medical'), (2, 'Others')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('document', models.FileField(blank=True, upload_to='clients/%Y/%m/%d/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('place_ob', models.CharField(blank=True, max_length=100, verbose_name='Place Of Birth')),
                ('date_ob', models.DateField(blank=True, null=True)),
                ('married', models.BooleanField(default=False)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('spouse_contact', models.CharField(blank=True, max_length=100)),
                ('num_children', models.IntegerField(default=0, verbose_name='Number Of Children')),
                ('home_town', models.CharField(blank=True, max_length=100)),
                ('prev_job', models.CharField(blank=True, max_length=100, verbose_name='Previous Job')),
                ('prev_employer', models.CharField(blank=True, max_length=200, verbose_name='Previous Employer')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('document', models.FileField(blank=True, upload_to='clients/%Y/%m/%d/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='Interpol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('clearance_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('document', models.FileField(blank=True, upload_to='clients/%Y/%m/%d/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('document', models.FileField(blank=True, upload_to='clients/%Y/%m/%d/')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('position_on_clearance', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Done'), (3, 'Cancelled'), (4, 'Passed'), (5, 'Failed')], default=0)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('clearance_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.clearancefile')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
            ],
        ),
    ]
