# Generated by Django 3.1.5 on 2021-01-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
