# Generated by Django 3.1.5 on 2021-02-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20210217_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ticket Number'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='visa_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Visa Number'),
        ),
    ]
