# Generated by Django 3.1.5 on 2021-02-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_client_trainings'),
        ('operations', '0005_auto_20210217_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelPlan',
            new_name='Travel',
        ),
    ]
