# Generated by Django 3.1.4 on 2021-01-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210105_1029'),
        ('finances', '0002_auto_20210104_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
